// Code generated by Slice Machine. DO NOT EDIT.

import AnotherReverse from './AnotherReverse/index.svelte';
import CaseStudies from './CaseStudies/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';
import Showcase from './Showcase/index.svelte';

export const components = {
	another_reverse: AnotherReverse,
	case_studies: CaseStudies,
	hero: Hero,
	rich_text: RichText,
	showcase: Showcase
};
